<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputType>WinExe</OutputType>
    <RootNamespace>BOG.BulkFileRename</RootNamespace>
    <AssemblyName>BOG.BulkFileRename</AssemblyName>
    <Deterministic>true</Deterministic>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Title>Bulk File Rename Utility</Title>
		<Version>2.0.2</Version>
		<AssemblyVersion>2.0.2.0</AssemblyVersion>
    <FileVersion>2.0.2.0</FileVersion>
    <StartupObject>BOG.BulkFileRename.Program</StartupObject>
    <AssemblyTitle>BOG.BulkFileRename</AssemblyTitle>
    <ApplicationIcon>icon\Movement.ico</ApplicationIcon>
    <Copyright>(c) 2009-2026, Bits Of Genius, licensed under the MIT license</Copyright>
    <PackageProjectUrl>https://github.com/rambotech/BOG.BulkFileRename</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/rambotech/BOG.BulkFileRename</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReleaseNotes>v2.0.2 -- .NET10</PackageReleaseNotes>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <DebugType>portable</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DefineConstants>TRACE</DefineConstants>
    <DebugType>portable</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="docs\BulkFileRename.pdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="icon\Movement.ico" />
    <Content Include="image\bogwf.bmp" />
    <Content Include="image\bog_495x315.bmp" />
    <Content Include="image\bog_495x60.bmp" />
    <Content Include="multitool.png" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BOG.SwissArmyKnife" Version="1.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BOG.BulkFileRenameCommon\BOG.BulkFileRename.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>